version: '3.5'

services:
  frontend:
    image: frontend 
    environment:
      - VIRTUAL_HOST=frontend
    container_name: frontend
    ports:
      - 5000:5000   
  backend:
    image: backend
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=example
      - DB_PASSWORD=example
      - DB_HOST=db_backendexample
      - VIRTUAL_HOST=backend
    container_name: backend
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend 
    ports:
      - 80:80
    container_name: web
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    container_name: db_backendexample

    
