version: '3.5'

services:
    frontend:
      image: frontend
      build: .
      ports:
      - 5000:5000
      container_name: frontend
    backend:
      image: backend
      build: .
      ports:
      - 8000:8000
      environment:
        - REDIS=redis
        - REDIS_PORT=6379
      container_name: backend
    redis:
      image: redis
      container_name: redis

